name: Jodie CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scala: [ "2.12.17", "2.13.10" ]
        spark: ["3.3.1","3.3.2"]
        delta: ["2.1.0","2.2.0"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Run tests
        run: sbt ++${{ matrix.scala }} test
        env:
          SPARK_VERSION: ${{ matrix.spark }}
          DELTA_VERSION: ${{ matrix.delta }}